FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH="/app/ots-common:$PYTHONPATH"
WORKDIR /app
COPY shared/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY shared/ ./shared/
COPY ots-common/ ./ots-common/
COPY gt_video_prep/ ./job/
CMD ["python", "job/main.py"]
